version: '3.6'

services:
  meta_learning_service:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: ${DOCKER_IMAGE_NAME}
    shm_size: 32G
    network_mode: host
    expose: 
      - ${sshd_port}
    dns_search:
      - cw01.contiwan.com
    environment:
      - DL_PLATFORM_ENVIRONMENT_TYPE=ONPREM
      - no_proxy=github.conti.de,eu-test.artifactory.conti.de,conti.de
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/.Xauthority
      - HOME=${HOME}
      - ORIG_USER_GID=${ORIG_USER_GID}
      - ORIG_DEV_GID=${ORIG_DEV_GID}
      - USER=${USER}
      - UID=${UID} # Needed by add_user script, For visibility one may have to `export UID` from bash
      - sshd_port=${sshd_port}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/.Xauthority
      - ..:/train/code  # mount the code
      - ${IMAGENET_PATH}:/train/data/imagenet  # mount imagenet data
      - ${IMAGENET84_PATH}:/train/data/imagenet84  # mount imagenet data
      - ${RESULTS_PATH}:/train/results  # mount the results dict
    working_dir: /train/code
    entrypoint:
      - /usr/bin/tini
      - "--"
      - /add_user.sh
